// Copyright 2026, starseaN contributors
// SPDX-License-Identifier: GPL-3.0

package app

/**
 * Default whitelist selection keys (`userId:packageName`).
 * Keep in sync with `assets/preset-apps.txt`.
 */
val PresetProxyAppPackageNames: List<String> = listOf(
    "0:com.android.chrome",
    "0:com.google.android.apps.bard",
    "0:li.songe.gkd",
    "0:com.google.android.googlequicksearchbox",
    "0:com.sevtinge.hyperceiler",
    "0:com.rifsxd.ksunext",
    "0:app.revanced.android.gms",
    "0:app.morphe.manager",
    "0:md.obsidian",
    "0:air.com.rosettastone.mobile.CoursePlayer",
    "0:com.scanauthgen",
    "0:org.telegram.messenger",
    "0:app.morphe.android.youtube",
    "0:com.android.providers.downloads.ui",
    "0:com.okinc.okex.gp",
    "0:com.google.android.ext.shared",
    "999:android",
    "999:com.miui.contentcatcher",
    "999:com.android.keychain",
    "999:com.miui.securitycore",
    "999:com.android.systemui",
    "999:com.android.server.telecom",
    "0:com.android.providers.media",
    "0:com.android.mtp",
    "0:com.android.providers.downloads",
    "0:com.android.soundpicker",
    "0:com.google.android.cellbroadcastreceiver.overlay.miui",
    "0:com.google.android.cellbroadcastservice.overlay.miui",
    "0:com.google.android.ncm.overlay.common",
    "0:com.google.android.overlay.gmsconfig",
    "0:com.google.android.uwb.resources.overlay.common",
    "0:com.google.android.wifi.resources.overlay.common",
    "0:com.google.android.wifi.resources.overlay.spf",
    "0:com.google.android.wifi.resources.overlay.target",
    "0:com.google.android.wifi.resources.xiaomi",
    "0:com.google.android.configupdater",
    "0:com.google.android.onetimeinitializer",
    "0:com.android.vending",
    "0:com.google.android.gms",
    "999:com.google.android.gms",
    "0:com.google.android.gms.location.history",
    "0:com.google.android.gsf",
    "999:com.google.android.gsf",
    "0:com.google.android.printservice.recommendation",
    "0:com.android.se",
    "0:com.google.android.accessibility.switchaccess",
    "0:com.google.android.documentsui",
    "0:com.github.android",
    "0:com.yangdai.opennote",
    "0:org.woheller69.whobird",
    "0:com.windyty.android",
    "0:com.google.android.apps.authenticator2",
)
