// Copyright 2026, starseaN contributors
// SPDX-License-Identifier: GPL-3.0

package engine.root.publication

import utils.shellQuote
import utils.shellQuoteForCase
import java.io.File

internal object RootLegacyMigrationCommand {
    fun appendGate(builder: StringBuilder, layout: RootRuntimeLayout) = with(builder) {
        val dataDir = File(layout.dataDir)
        val legacy = listOf(
            File(dataDir, "config-root.json"), File(dataDir, "xray-root.pid"),
            File(dataDir, "starsead.pid"), File(dataDir, "starsead.ready"),
            File(dataDir, "stop.sh"), File(dataDir, "bpf-policy.json"),
            File(dataDir, "bpf2socks.json"), File(dataDir, "bpf2socks.pid"),
            File(dataDir, "tun2socks.pid"), File(dataDir, "logs/starsead.log"),
            File(layout.starseadStatePath),
            File("${layout.starseadStatePath}.route-localnet"),
        )
        val pidFiles = legacy.filter { it.name.endsWith(".pid") }
        val legacyTunPid = File(dataDir, "tun2socks.pid")
        appendLine("legacy_migrate() {")
        appendLine("  if { [ -f ${layout.starseadConfigPath.shellQuote()} ] && grep -Eq '\"schemaVersion\"[[:space:]]*:[[:space:]]*[23]([,}])' ${layout.starseadConfigPath.shellQuote()}; } ||")
        appendLine("     { [ -f ${layout.starseadStatePath.shellQuote()} ] && grep -Eq '\"schemaVersion\"[[:space:]]*:[[:space:]]*2([,}])' ${layout.starseadStatePath.shellQuote()}; }; then")
        appendLine("    return 0")
        appendLine("  fi")
        appendLine("  legacy_seen=0")
        legacy.forEach { file -> appendLine("  { [ -e ${file.absolutePath.shellQuote()} ] || [ -L ${file.absolutePath.shellQuote()} ]; } && legacy_seen=1") }
        appendLine("  [ \"\$legacy_seen\" -eq 1 ] || return 0")
        appendLine("  [ -f ${layout.starseadConfigPath.shellQuote()} ] && [ ! -L ${layout.starseadConfigPath.shellQuote()} ] || return 76")
        appendLine("  grep -Eq '\"version\"[[:space:]]*:[[:space:]]*3([,}])' ${layout.starseadConfigPath.shellQuote()} || return 76")
        appendLine("  grep -F -q -- ${layout.starseadStatePath.shellQuote()} ${layout.starseadConfigPath.shellQuote()} || return 76")
        appendLine("  grep -F -q -- ${File(dataDir, "stop.sh").absolutePath.shellQuote()} ${layout.starseadConfigPath.shellQuote()} || return 76")
        appendLine("  if [ -e ${legacyTunPid.absolutePath.shellQuote()} ]; then")
        appendLine("    grep -F -q -- ${legacyTunPid.absolutePath.shellQuote()} ${layout.starseadConfigPath.shellQuote()} || return 76")
        appendLine("  fi")
        appendLine("  legacy_uid=\"$(stat -c %u ${layout.dataDir.shellQuote()})\" || return 76")
        legacy.forEach { file ->
            appendLine("  if [ -e ${file.absolutePath.shellQuote()} ] || [ -L ${file.absolutePath.shellQuote()} ]; then")
            appendLine("    [ -f ${file.absolutePath.shellQuote()} ] && [ ! -L ${file.absolutePath.shellQuote()} ] || return 76")
            appendLine("    legacy_file_uid=\"$(stat -c %u ${file.absolutePath.shellQuote()})\" || return 76")
            appendLine("    [ \"\$legacy_file_uid\" = 0 ] || [ \"\$legacy_file_uid\" = \"\$legacy_uid\" ] || return 76")
            appendLine("  fi")
        }
        pidFiles.forEach { file -> appendLine("  if [ -s ${file.absolutePath.shellQuote()} ]; then grep -Eq '^[1-9][0-9]*[[:space:]]*$' ${file.absolutePath.shellQuote()} || return 76; fi") }
        appendLine("  if [ -e ${File(dataDir, "stop.sh").absolutePath.shellQuote()} ]; then")
        appendLine("    grep -F -q -- 'Generated by starseaN' ${File(dataDir, "stop.sh").absolutePath.shellQuote()} || return 76")
        appendLine("  fi")
        appendLine("  for legacy_proc in /proc/[0-9]*; do")
        appendLine("    [ -d \"\$legacy_proc\" ] || continue")
        appendLine("    legacy_pid=\"\${legacy_proc##*/}\"")
        appendLine("    case \"\$legacy_pid\" in")
        appendLine("      ''|*[!0-9]*) continue ;;")
        appendLine("    esac")
        appendLine("    [ \"\$legacy_pid\" = \"\$\$\" ] && continue")
        appendLine("    [ -r \"\$legacy_proc/cmdline\" ] && [ -r \"\$legacy_proc/status\" ] || return 76")
        appendLine("    legacy_cmdline=\"$(tr '\\0' ' ' < \"\$legacy_proc/cmdline\")\" || return 76")
        appendLine("    case \"\$legacy_cmdline\" in")
        appendLine("      *${File(dataDir, "config-root.json").absolutePath.shellQuoteForCase()}*|*${layout.starseadConfigPath.shellQuoteForCase()}*)")
        appendLine("        legacy_uid_line=\"$(grep '^Uid:' \"\$legacy_proc/status\")\" || return 76")
        appendLine("        set -- \$legacy_uid_line")
        appendLine("        [ \"\$3\" != 0 ] && [ \"\$5\" != 0 ] || return 76")
        appendLine("        ;;")
        appendLine("    esac")
        appendLine("  done")
        legacy.forEach { file ->
            appendLine("  if [ -e ${file.absolutePath.shellQuote()} ]; then")
            appendLine("    rm -f -- ${file.absolutePath.shellQuote()} || return 76")
            appendLine("  fi")
        }
        appendLine("}")
        appendLine("legacy_migrate")
    }
}
